# Generated by Django 3.0.8 on 2020-08-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('abstract', models.CharField(max_length=300)),
                ('graph', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('anthor_name', models.CharField(max_length=20)),
                ('published_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('readings', models.IntegerField(default=0)),
                ('flag', models.BooleanField()),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('sort_id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Sort',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_headimg', models.CharField(max_length=100)),
                ('com_name', models.CharField(max_length=20)),
                ('com_email', models.CharField(max_length=20)),
                ('com_pubtime', models.DateTimeField(auto_now_add=True)),
                ('com_content', models.TextField()),
                ('con_like', models.IntegerField(default=0)),
                ('com_dislike', models.IntegerField(default=0)),
                ('com_reply', models.TextField()),
                ('com_flag', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Sort'),
        ),
    ]
