# Generated by Django 3.0.8 on 2020-08-02 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '评论'},
        ),
        migrations.AlterModelOptions(
            name='sort',
            options={'verbose_name': '分类'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户管理'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='anthor_name',
        ),
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(default=222, max_length=20, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(max_length=300, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='flag',
            field=models.BooleanField(verbose_name='标记'),
        ),
        migrations.AlterField(
            model_name='article',
            name='graph',
            field=models.CharField(max_length=100, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='喜欢'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='readings',
            field=models.IntegerField(default=0, verbose_name='阅读'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Sort', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='com_content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='com_dislike',
            field=models.IntegerField(default=0, verbose_name='不喜欢'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='com_email',
            field=models.CharField(max_length=20, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='com_flag',
            field=models.BooleanField(verbose_name='标记'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='com_headimg',
            field=models.CharField(max_length=100, verbose_name='评论头像'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='com_name',
            field=models.CharField(max_length=20, verbose_name='评论者名称'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='com_pubtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='com_reply',
            field=models.TextField(verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='con_like',
            field=models.IntegerField(default=0, verbose_name='喜欢'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='sort_name',
            field=models.CharField(max_length=20, verbose_name='类名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_name',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, verbose_name='密码'),
        ),
    ]
