# Generated by Django 3.0.8 on 2020-08-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200802_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_name',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=2, max_length=30, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
