# Generated by Django 3.0.8 on 2020-08-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comments_com_headimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='com_reply',
        ),
    ]
